### ISSUE TITLE
在 Termux 中第一次启动有概率崩溃

### ISSUE THREAD

**Issue by Henry-ZHR** [Kr328/file-monitor#1]
冷启动 Termux，然后 `sudo file-monitor`，一两秒后 file-monitor 退出，返回值 2

[输出](https://gist.github.com/Henry-ZHR/63ec1cf3a82e9b8d8e30c8487681fb13)

另外注意到一个现象，在发生上述崩溃的情况下，Magisk 的 Toast 会变成 `[UID] XXX 已…` 而非 `Termux 已…`（该现象并不只在运行 file-monitor 时发生）

---

file-monitor ec8e5ae

Magisk 25.1

设备 Motorola Edge S；LineageOS 18.1 official 的源码，唯一修改是 `CONFIG_KPROBES`

**Comment by Henry-ZHR** [comment]
多次重复尝试复现时复现概率较低

**Comment by Kr328** [comment]
为什么还有人用这个啊.webp (令人感慨

**Comment by Henry-ZHR** [comment]
~~这就得问 Rikka 的文件监视为什么这么残废了~~

**Comment by Kr328** [comment]
[file-monitor-amd64.gz](https://github.com/Kr328/file-monitor/files/9077296/file-monitor-amd64.gz)
[file-monitor-arm.gz](https://github.com/Kr328/file-monitor/files/9077297/file-monitor-arm.gz)
[file-monitor-arm64.gz](https://github.com/Kr328/file-monitor/files/9077298/file-monitor-arm64.gz)
[file-monitor-i386.gz](https://github.com/Kr328/file-monitor/files/9077299/file-monitor-i386.gz)

该试试了

**Comment by Henry-ZHR** [comment]
90dd68180edcbd69b8d7cc87126e936edbefa215，确实是不会崩溃了

不过看源码，现在是直接忽略为空的吗，是什么情况下会产生空的呢？

**Comment by Kr328** [comment]
别问 问就是不知道 不知道内核的那个参数为什么是空的
